### ISSUE TITLE
Package name and scope

### ISSUE THREAD

**Issue by shaedrich** [hotmeteor/titles#2]
* Should the package be limited to titles only? Since most style guides extend their applicability to other stuff like hyphenation or quote style
* Should we include some automatic corrections like for quotes (similar to what Microsoft Word does)?

**Comment by hotmeteor** [comment]
I've also seen date formatting

**Comment by shaedrich** [comment]
* Title casing
* Date formatting
* Special character transliteration (quotes, dashes, etc.)
* Grammatical speech preferences (hyphenation, contractions, etc.)
